"""Убрал поле Количество у таблицы наборов

Revision ID: 0249759985c3
Revises: 27fa11120115
Create Date: 2025-02-20 10:59:11.341413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0249759985c3'
down_revision: Union[str, None] = '27fa11120115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
