"""Починил внешние ключи у таблиц

Revision ID: 463487eaaa57
Revises: 61aeb99662ba
Create Date: 2025-02-06 20:40:11.324094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463487eaaa57'
down_revision: Union[str, None] = '61aeb99662ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipients_patient_id_fkey', 'recipients', type_='foreignkey')
    op.create_foreign_key(None, 'recipients', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipients', type_='foreignkey')
    op.create_foreign_key('recipients_patient_id_fkey', 'recipients', 'mailing_delivery_methods', ['patient_id'], ['id'])
    # ### end Alembic commands ###
