"""Добавил таблицу с содержанием набора

Revision ID: 7d74a745da7a
Revises: c0997c6bf2f1
Create Date: 2025-02-18 11:28:51.401555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d74a745da7a'
down_revision: Union[str, None] = 'c0997c6bf2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tor', sa.Integer(), nullable=False),
    sa.Column('trial', sa.Integer(), nullable=False),
    sa.Column('esa', sa.Integer(), nullable=False),
    sa.Column('fvc', sa.Integer(), nullable=False),
    sa.Column('preset_refraction', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('periphery_toricity', sa.Integer(), nullable=False),
    sa.Column('side', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_contents')
    # ### end Alembic commands ###
