"""добавил признак выдачи у линз

Revision ID: c0997c6bf2f1
Revises: 463487eaaa57
Create Date: 2025-02-13 20:35:52.618925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0997c6bf2f1'
down_revision: Union[str, None] = '463487eaaa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lens', sa.Column('issued', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lens', 'issued')
    # ### end Alembic commands ###
